name:                svg-transform
version:             0.1.0.0
github:              "foundling/svg-transform"
license:             BSD3
author:              "Alex Ramsdell"
maintainer:          "alexramsdell@gmail.com"
copyright:           "2018 Alex Ramsdell"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/foundling/svg-transform#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  svg-transform-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - svg-transform

tests:
  svg-transform-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - svg-transform
    - QuickCheck
